# General
logging.level.root=INFO
server.port=${PORT:8080}
logging.level.org.springframework=INFO
logging.level.org.springframework.web.reactive=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# H2 R2DBC
spring.r2dbc.url=r2dbc:h2:mem:///studentdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

# Schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# H2 Console
spring.h2.console.enabled=false
# Cambia a true para habilitar la consola H2 junto con implementation 'org.springframework.boot:spring-boot-starter-web' en build.gradle.
spring.h2.console.path=/h2-console
# LOG DEBUG para R2DBC de H2
#logging.level.org.springframework.r2dbc.core=DEBUG
#logging.level.io.r2dbc.h2=DEBUG

# JDBC (para consola)
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver





