# General
logging.level.root=INFO
server.port=8080
logging.level.org.springframework=INFO
logging.level.org.springframework.web.reactive=DEBUG

# H2 R2DBC
spring.r2dbc.url=r2dbc:h2:mem:///studentdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

# Schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# lOG
#logging.level.org.springframework.r2dbc.core=DEBUG
#logging.level.io.r2dbc.h2=DEBUG

# JDBC (para consola)
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver





